env:
  node: true
  browser: true
  commonjs: true
  es2021: true
  jquery: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  semi:
    - error
    - always
